docker pull logimethods/smart-meter:telegraf
docker pull logimethods/smart-meter:prometheus
docker pull logimethods/smart-meter:cassandra-inject
docker pull logimethods/smart-meter:cassandra
docker pull logimethods/smart-meter:inject
docker pull logimethods/smart-meter:monitor
docker pull logimethods/ek_nats-server
docker pull logimethods/ek_nats-client
docker pull logimethods/smart-meter:app-batch
docker pull logimethods/smart-meter:app-streaming
docker pull logimethods/prometheus-nats-exporter
docker pull logimethods/eureka
