NATS_USERNAME=${NATS_USERNAME:=`cat ${NATS_USERNAME_FILE:=NATS_USERNAME_FILE}`}
NATS_PASSWORD=${NATS_PASSWORD:=`cat ${NATS_PASSWORD_FILE:=NATS_PASSWORD_FILE}`}
export NATS_URI="nats://${NATS_USERNAME}:${NATS_PASSWORD}@${NATS_NAME}:4222"
