export NATS_USERNAME=`cat ${NATS_USERNAME_FILE}`
export NATS_PASSWORD=`cat ${NATS_PASSWORD_FILE}`

export NATS_CLUSTER_USERNAME=`cat ${NATS_CLUSTER_USERNAME_FILE}`
export NATS_CLUSTER_PASSWORD=`cat ${NATS_CLUSTER_PASSWORD_FILE}`
